name: Changesets

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  Publish:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
     
      - name: Install pnpm
        run: npm i pnpm@latest -g
      
      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      
      - name: Setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER
      
      - name: Install sependencies
        run: pnpm install
      
      - name: Create and publish versions
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run version
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Send a slack notification if a publish happens
        if: steps.changesets.outputs.published == 'true'
        # You can do something when a publish happens.
        run: my-slack-bot send-notification --message "A new version of ${GITHUB_REPOSITORY} was published!"